### ISSUE TITLE
디자인 페이지 추가 작업

### ISSUE THREAD

**Issue by jeonjunhyeon** [TP1-Competition/MilRoute#73]
⭐ 주요 작업
메인페이지의 아웃라인 디자인

📋 상세 작업 목록
 - [x] 메인페이지의 아웃라인 디자인 초안 작업
 - [x] 메인페이지의 아웃라인 디자인 수정 작업

**Comment by jeonjunhyeon** [comment]
- 메인 페이지 아웃라인 디자인 초안 작업 완료
- 해당 디자인 이미지 첨부

![Page24](https://github.com/TP1-Competition/MilRoute/assets/78460487/91295dc1-70d1-4231-a3f8-12e4bd917bdd)

**Comment by y00eunji** [comment]
오 완전 잘하셨네요
